name: CI Pipeline

on:
  pull_request:
    branches:
      - master  # or any branch you want to run tests on

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'  # specify the Java version you're using

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Generate Unit Test Report
      run: |
        mkdir -p reports/unit-tests
        cp -r build/test-results/test/* reports/unit-tests/
      continue-on-error: true

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run E2E Tests
      run: ./gradlew e2eTest # Assuming your e2e tests are under e2eTest task

    - name: Generate E2E Test Report
      run: |
        mkdir -p reports/e2e-tests
        cp -r build/test-results/e2eTest/* reports/e2e-tests/
      continue-on-error: true

  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Code Coverage
      run: ./gradlew jacocoTestReport

    - name: Check Coverage Report
      run: cat build/reports/jacoco/test/html/index.html
      continue-on-error: true

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: build/reports/jacoco/test/html/
